name: Cypress Tests

on:
  push:
    branches:
      - staging

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout
        uses: actions/checkout@v4
        with: 
          path: server

      - name: Start Server BackEnd
        run: |
          cd server
          npm install
          npm start &
          until [ "$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)" == "200" ]; do
            echo "Waiting for server to start..."
            sleep 1
          done
          echo "Server is running successfully."
        working-directory: server

      - name: Configurar Variável de Ambiente
        run: echo "DB_ENV=${{ secrets.DB_ENV }}" > server/.env

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          config: pageLoadTimeout=100000,baseUrl=http://localhost:8080
          spec: cypress/e2e/api/login-api.cy.js
          wait-on: 'http://localhost:8080'

    env:
        browser: chrome
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}